# Generated by Django 5.0.7 on 2024-07-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_full_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumb_image',
        ),
    ]
